library(float)
completo <- read.csv2("C:/Users/Luis Toro/Documents/GitHub/Cenacad/completo.csv",header = F)
names(completo) = c("anio","semestre","codigo_materia","materia","paralelo","profesor","pregunta","media","desviacion")
general <- cbind.data.frame(completo$pregunta,as.numeric(levels(completo$media))[completo$media],as.numeric(levels(completo$desviacion))[completo$desviacion],stringsAsFactors = FALSE)
names(general)=c("Pregunta","Media","Desviacion")
summary(general)
str(general)
#is.atomic(general$Media)
#cor(general$Media,general$Desviacion)
plot(general$Pregunta,general$Media)
plot(general$Pregunta,general$Desviacion)
#cor.test(general)
hist(general$Media)
hist(general$Desviacion)
#hist(general$Desviacion)
preguntas <- as.factor(general$Pregunta)
summary(preguntas)
pregunta1<-cbind.data.frame(general$Pregunta[general$Pregunta==preguntas[1]],as.numeric(levels(general$Media[general$Pregunta==preguntas[1]]))[general$Media[general$Pregunta==preguntas[1]]],as.numeric(levels(general$Desviacion[general$Pregunta==preguntas[1]]))[general$Desviacion[general$Pregunta==preguntas[1]]])
pregunta2<-cbind.data.frame(general$Pregunta[general$Pregunta==preguntas[2]],general$Media[general$Pregunta==preguntas[2]],general$Desviacion[general$Pregunta==preguntas[2]])
pregunta3<-cbind.data.frame(general$Pregunta[general$Pregunta==preguntas[3]],general$Media[general$Pregunta==preguntas[3]],general$Desviacion[general$Pregunta==preguntas[3]])
pregunta4<-cbind.data.frame(general$Pregunta[general$Pregunta==preguntas[4]],general$Media[general$Pregunta==preguntas[4]],general$Desviacion[general$Pregunta==preguntas[4]])
pregunta5<-cbind.data.frame(general$Pregunta[general$Pregunta==preguntas[5]],general$Media[general$Pregunta==preguntas[5]],general$Desviacion[general$Pregunta==preguntas[5]])
pregunta6<-cbind.data.frame(general$Pregunta[general$Pregunta==preguntas[6]],general$Media[general$Pregunta==preguntas[6]],general$Desviacion[general$Pregunta==preguntas[6]])
pregunta7<-cbind.data.frame(general$Pregunta[general$Pregunta==preguntas[7]],general$Media[general$Pregunta==preguntas[7]],general$Desviacion[general$Pregunta==preguntas[7]])
pregunta8<-cbind.data.frame(general$Pregunta[general$Pregunta==preguntas[8]],general$Media[general$Pregunta==preguntas[8]],general$Desviacion[general$Pregunta==preguntas[8]])
pregunta9<-cbind.data.frame(general$Pregunta[general$Pregunta==preguntas[9]],general$Media[general$Pregunta==preguntas[9]],general$Desviacion[general$Pregunta==preguntas[9]])
pregunta10<-cbind.data.frame(general$Pregunta[general$Pregunta==preguntas[10]],general$Media[general$Pregunta==preguntas[10]],general$Desviacion[general$Pregunta==preguntas[10]])
pregunta11<-cbind.data.frame(general$Pregunta[general$Pregunta==preguntas[11]],general$Media[general$Pregunta==preguntas[11]],general$Desviacion[general$Pregunta==preguntas[11]])
pregunta12<-cbind.data.frame(general$Pregunta[general$Pregunta==preguntas[12]],general$Media[general$Pregunta==preguntas[12]],general$Desviacion[general$Pregunta==preguntas[12]])
(pregunta1$`general$Media[general$Pregunta == preguntas[1]]`)
as.numeric(levels(pregunta1$`general$Media[general$Pregunta == preguntas[1]]`))
summary(pregunta1)
