library(float)
completo <- read.csv2("C:/Users/Luis Toro/Documents/GitHub/Cenacad/completo.csv",header = F)
names(completo) = c("anio","semestre","codigo_materia","materia","paralelo","profesor","pregunta","media","desviacion")
general <- cbind.data.frame(completo$pregunta,as.data.frame.numeric(completo$media),as.data.frame.numeric(completo$desviacion),stringsAsFactors = FALSE)
names(general)=c("Pregunta","Media","Desviacion")
summary(general)
str(general)
#is.atomic(general$Media)
#cor(general$Media,general$Desviacion)
#plot(general$Pregunta,general$Media)
#plot(general$Pregunta,general$Desviacion)
#cor.test(general)
#hist(general$Media)
#hist(general$Desviacion)
pregunta1 <- as.factor(general$Pregunta)
summary(pregunta1)
h<-(general$Pregunta[general$Pregunta==pregunta1[1]])
h
