library(float)
completo <- read.csv2("C:/Users/Luis Toro/Documents/GitHub/Cenacad/completo.csv",header = F)
names(completo) = c("anio","semestre","codigo_materia","materia","paralelo","profesor","pregunta","media","desviacion")
general <- cbind.data.frame(completo$pregunta,(completo$media),(completo$desviacion))
names(general)=c("Pregunta","Media","Desviacion")
pregunta1 <- (general$Pregunta["Explica con claridad las polÃ???ticas y los objetivos de aprendizaje, cumpliendo con los contenidos de la materia."])
summary(general)
str(general)
is.atomic(general$Media)
cor(general$Media,general$Desviacion)
plot(general$Pregunta,general$Media)
plot(general$Pregunta,general$Desviacion)
cor.test(general)
hist(general$Media)
hist(general$Desviacion)
pregunta1
